---
title: HKIS Dragons
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  teams:
    title: Teams
    output: true
    permalink: "/:collection-:name"
  uploads:
    title: Uploads
    output: true
future: true
sass:
  style: compressed
exclude:
- README.md
- Gemfile.lock
- Gemfile
- LICENSE.txt
- hkisdragons.gemspec
permalink: "/:title/"
