---
title: HKIS Dragons
timezone: UTC
collections:
  collectiontwo:
    title: CollectionTwo
    output: true
  one:
    title: One
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
exclude:
- README.md
- Gemfile.lock
- Gemfile
- LICENSE.txt
- hkisdragons.gemspec
