---
title: HKIS Dragons
timezone: UTC
collections:
  apac-basketball:
    title: APAC Basketball
    output: true
  china-cup-rugby:
    title: China Cup Rugby
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
exclude:
- README.md
- Gemfile.lock
- Gemfile
- LICENSE.txt
- hkisdragons.gemspec
permalink: "/:title/"
