---
title: HKIS Dragons
timezone: UTC
collections:
  china-cup-volleyball:
    title: China Cup Volleyball
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
sass:
  style: compressed
exclude:
- README.md
- Gemfile.lock
- Gemfile
- LICENSE.txt
- hkisdragons.gemspec
